// SPDX-License-Identifier: Apache-2.0

// Package remote implements storage.Storage by talking the HTTP
// protocol defined in docs/adapters/protocols/storage-v1.md to a
// sidecar adapter. Selected via AF_STACK_STORAGE_ADAPTER=remote.
//
// One Adapter per AF_STACK_STORAGE_ADAPTER_URL. Goroutine-safe; the
// underlying remote.Client owns the connection pool.
package remote

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/Agent-Field/backai/services/runtime/internal/adapters/remote"
	"github.com/Agent-Field/backai/services/runtime/internal/storage"
)

// Adapter is a storage.Storage backed by a remote sidecar speaking the
// storage-v1 protocol.
type Adapter struct {
	client *remote.Client
	caps   storage.Capabilities
	name   string // active adapter name from /v1/capabilities

	// CachedAt is the time we last refreshed capabilities. Exposed
	// for tests and the operator-facing /admin/adapters status.
	CachedAt time.Time
}

// Compile-time interface check.
var _ storage.Storage = (*Adapter)(nil)

// Config is the env-driven configuration. Use NewFromEnv for the
// canonical wire-up.
type Config struct {
	BaseURL    string
	Token      string
	Timeout    time.Duration
	MaxRetries int
}

// New returns an Adapter for the given config. Performs a synchronous
// GET /v1/capabilities to verify the sidecar speaks the protocol; if
// that call fails, returns the error so the runtime can refuse to start
// (rather than discovering the problem on the first user request).
func New(ctx context.Context, cfg Config) (*Adapter, error) {
	if strings.TrimSpace(cfg.BaseURL) == "" {
		return nil, errors.New("storage/remote: BaseURL required")
	}
	if cfg.Timeout <= 0 {
		cfg.Timeout = 30 * time.Second
	}
	if cfg.MaxRetries < 0 {
		cfg.MaxRetries = 2
	}
	c, err := remote.NewClient(remote.Config{
		BaseURL:    cfg.BaseURL,
		Token:      cfg.Token,
		Timeout:    cfg.Timeout,
		MaxRetries: cfg.MaxRetries,
	})
	if err != nil {
		return nil, fmt.Errorf("storage/remote: client: %w", err)
	}

	a := &Adapter{client: c}
	if err := a.refreshCapabilities(ctx); err != nil {
		return nil, fmt.Errorf("storage/remote: capabilities probe: %w", err)
	}
	return a, nil
}

// refreshCapabilities pulls /v1/capabilities and decodes the slot-
// specific shape into our typed storage.Capabilities.
func (a *Adapter) refreshCapabilities(ctx context.Context) error {
	resp, err := a.client.Capabilities(ctx)
	if err != nil {
		return err
	}
	if resp.Slot != "storage" {
		return fmt.Errorf("storage/remote: adapter reports slot=%q; expected storage", resp.Slot)
	}
	a.name = resp.Name
	var caps storageCaps
	if len(resp.Capabilities) > 0 {
		if err := json.Unmarshal(resp.Capabilities, &caps); err != nil {
			return fmt.Errorf("storage/remote: decode capabilities: %w", err)
		}
	}
	a.caps = storage.Capabilities{
		MaxObjectSizeBytes:   caps.MaxObjectSizeBytes,
		SupportsMultipart:    caps.SupportsMultipart,
		PresignTTLMaxSeconds: caps.PresignTTLMaxSeconds,
	}
	a.CachedAt = time.Now()
	return nil
}

// Name returns the active adapter's name (from /v1/capabilities). Used
// by the registry to populate /api/v1/admin/adapters.
func (a *Adapter) Name() string {
	if a == nil {
		return ""
	}
	return a.name
}

// Upload implements storage.Storage by streaming r to PUT /v1/objects/{key}.
// Metadata is sent as headers; Content-Type is mirrored to X-BackAI-Content-Type.
func (a *Adapter) Upload(ctx context.Context, key string, r io.Reader, opts storage.UploadOpts) (*storage.Object, error) {
	if key == "" {
		return nil, errors.New("storage/remote: key required")
	}

	// Build headers for metadata.
	headers := make(http.Header)
	if opts.ContentType != "" {
		headers.Set("Content-Type", opts.ContentType)
		headers.Set(remote.HeaderContentType, opts.ContentType)
	}
	for k, v := range opts.Metadata {
		headers.Set("X-BackAI-Metadata-"+k, v)
	}

	resp, err := a.client.Do(ctx, remote.Request{
		Method:       http.MethodPut,
		Path:         "/v1/objects/" + url.PathEscape(key),
		BodyReader:   r,
		ContentType:  opts.ContentType,
		ExtraHeaders: headers,
		// Idempotency key is generated by client if not provided
	})
	if err != nil {
		return nil, err
	}

	var wire objectWire
	if err := resp.DecodeJSON(&wire); err != nil {
		return nil, fmt.Errorf("storage/remote: decode upload response: %w", err)
	}

	lastMod, _ := time.Parse(time.RFC3339, wire.LastModified)
	return &storage.Object{
		Key:          wire.Key,
		Size:         wire.Size,
		ContentType:  wire.ContentType,
		LastModified: lastMod,
		ETag:         wire.ETag,
	}, nil
}

// Download implements storage.Storage by GET /v1/objects/{key}.
// Returns the raw response body as io.ReadCloser; the caller MUST close it.
// 404 errors are wrapped with storage.ErrNotFound.
func (a *Adapter) Download(ctx context.Context, key string) (io.ReadCloser, *storage.Object, error) {
	if key == "" {
		return nil, nil, errors.New("storage/remote: key required")
	}

	resp, err := a.client.Do(ctx, remote.Request{
		Method: http.MethodGet,
		Path:   "/v1/objects/" + url.PathEscape(key),
		Stream: true,
	})
	if err != nil {
		// Wrap 404 with storage.ErrNotFound sentinel.
		if remote.IsCode(err, "object_not_found") {
			return nil, nil, storage.ErrNotFound
		}
		return nil, nil, err
	}

	// Extract object metadata from response headers.
	lastMod, _ := time.Parse(time.RFC1123, resp.Header.Get("Last-Modified"))
	obj := &storage.Object{
		Key:          key,
		Size:         resp.ContentLength,
		ContentType:  resp.Header.Get("Content-Type"),
		LastModified: lastMod,
		ETag:         resp.Header.Get("ETag"),
	}

	return resp.Body, obj, nil
}

// SignedURL implements storage.Storage by POST /v1/objects/{key}/signed-url.
// Returns a time-limited URL the caller can present directly to clients.
func (a *Adapter) SignedURL(ctx context.Context, key string, ttl time.Duration) (string, error) {
	if key == "" {
		return "", errors.New("storage/remote: key required")
	}

	reqBody := signedURLRequest{
		TTLSeconds: int(ttl.Seconds()),
		Method:     "GET",
	}

	resp, err := a.client.Do(ctx, remote.Request{
		Method: http.MethodPost,
		Path:   "/v1/objects/" + url.PathEscape(key) + "/signed-url",
		Body:   reqBody,
	})
	if err != nil {
		return "", err
	}

	var wire signedURLResponse
	if err := resp.DecodeJSON(&wire); err != nil {
		return "", fmt.Errorf("storage/remote: decode signed-url response: %w", err)
	}

	return wire.URL, nil
}

// Delete implements storage.Storage by DELETE /v1/objects/{key}.
// Idempotent: deleting a missing key is not an error.
func (a *Adapter) Delete(ctx context.Context, key string) error {
	if key == "" {
		return errors.New("storage/remote: key required")
	}

	resp, err := a.client.Do(ctx, remote.Request{
		Method: http.MethodDelete,
		Path:   "/v1/objects/" + url.PathEscape(key),
	})
	if err != nil {
		// 404 on delete is idempotent — not an error.
		if remote.IsCode(err, "object_not_found") {
			return nil
		}
		return err
	}

	_ = resp.DecodeJSON(&struct{}{})
	return nil
}

// List implements storage.Storage by GET /v1/objects?prefix=...&token=...&limit=...
// Returns up to limit objects under prefix, with a pagination token.
func (a *Adapter) List(ctx context.Context, prefix, nextToken string, limit int) (*storage.ListResult, error) {
	q := url.Values{}
	if prefix != "" {
		q.Set("prefix", prefix)
	}
	if nextToken != "" {
		q.Set("token", nextToken)
	}
	if limit > 0 {
		q.Set("limit", fmt.Sprintf("%d", limit))
	}

	resp, err := a.client.Do(ctx, remote.Request{
		Method: http.MethodGet,
		Path:   "/v1/objects",
		Query:  q,
	})
	if err != nil {
		return nil, err
	}

	var wire listResultWire
	if err := resp.DecodeJSON(&wire); err != nil {
		return nil, fmt.Errorf("storage/remote: decode list response: %w", err)
	}

	// Convert wire objects to storage.Object.
	objects := make([]storage.Object, len(wire.Objects))
	for i, wo := range wire.Objects {
		lastMod, _ := time.Parse(time.RFC3339, wo.LastModified)
		objects[i] = storage.Object{
			Key:          wo.Key,
			Size:         wo.Size,
			ContentType:  wo.ContentType,
			LastModified: lastMod,
			ETag:         wo.ETag,
		}
	}

	return &storage.ListResult{
		Objects:   objects,
		Prefix:    wire.Prefix,
		NextToken: wire.NextToken,
	}, nil
}

// EnsureBucket implements storage.Storage by POST /v1/bucket/ensure.
// Idempotent: calling multiple times returns success.
func (a *Adapter) EnsureBucket(ctx context.Context) error {
	resp, err := a.client.Do(ctx, remote.Request{
		Method: http.MethodPost,
		Path:   "/v1/bucket/ensure",
		Body:   struct{}{},
	})
	if err != nil {
		return err
	}

	var result struct {
		Ensured bool `json:"ensured"`
	}
	if err := resp.DecodeJSON(&result); err != nil {
		return fmt.Errorf("storage/remote: decode ensure-bucket response: %w", err)
	}

	return nil
}

// Capabilities implements storage.Storage by returning cached capabilities
// from /v1/capabilities (fetched at New()).
func (a *Adapter) Capabilities() storage.Capabilities {
	if a == nil {
		return storage.Capabilities{}
	}
	return a.caps
}

// --- wire shapes ---------------------------------------------------------

type storageCaps struct {
	MaxObjectSizeBytes   int64 `json:"max_object_size_bytes"`
	SupportsMultipart    bool  `json:"supports_multipart"`
	PresignTTLMaxSeconds int   `json:"presign_ttl_max_seconds"`
}

type objectWire struct {
	Key          string `json:"key"`
	Size         int64  `json:"size"`
	ContentType  string `json:"content_type"`
	ETag         string `json:"etag"`
	LastModified string `json:"last_modified"`
}

type signedURLRequest struct {
	TTLSeconds int    `json:"ttl_seconds"`
	Method     string `json:"method"`
}

type signedURLResponse struct {
	URL       string `json:"url"`
	ExpiresAt string `json:"expires_at"`
	Method    string `json:"method"`
}

type listResultWire struct {
	Objects   []objectWire `json:"objects"`
	Prefix    string       `json:"prefix"`
	NextToken string       `json:"next_token"`
}
