{{- if .Values.autoscaling.runtime.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "af-stack.runtime.fullname" . }}
  labels:
    {{- include "af-stack.runtime.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "af-stack.runtime.fullname" . }}
  minReplicas: {{ .Values.autoscaling.runtime.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.runtime.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.runtime.targetCPUUtilization }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.runtime.targetCPUUtilization }}
    {{- end }}
    {{- if .Values.autoscaling.runtime.targetMemoryUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.runtime.targetMemoryUtilization }}
    {{- end }}
{{- end }}
