// SPDX-License-Identifier: Apache-2.0

package secrets

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"strings"
)

// CipherVersionV1 is the first (and currently only) on-disk format byte.
// Future formats — e.g. v2 with per-tenant DEK wrapping — bump this byte
// so we can migrate gracefully.
const CipherVersionV1 byte = 0x01

// CurrentKeyID is the kms_key_id value stored alongside ciphertext when
// the KEK directly wraps secret values. Phase 6 will replace this with
// per-tenant DEK IDs.
const CurrentKeyID = "v1"

// devKEKSentinel is the well-known placeholder we accept in dev. Anything
// matching this (case-insensitive) generates a deterministic dev KEK and
// logs a loud warning.
const devKEKSentinel = "dev-secret-change-me"

// devKEKSeed is hashed to produce the deterministic dev KEK when the env
// var is missing or set to the sentinel.
const devKEKSeed = "af-stack-dev-kek"

// kekSize is the AES-256 key length in bytes.
const kekSize = 32

// gcmNonceSize is the standard AES-GCM nonce length.
const gcmNonceSize = 12

// Cipher wraps a configured AEAD instance and the key id used to label
// stored ciphertext. The plaintext key never leaves the struct.
type Cipher struct {
	aead    cipher.AEAD
	keyID   string
	devMode bool
}

// LoadKEK reads AF_STACK_KMS_KEY (hex-encoded 32 bytes). When the env
// var is empty or matches devKEKSentinel, a deterministic dev KEK is
// generated by sha256(devKEKSeed) and a clear WARN is logged.
//
// log is used only for the dev-mode warning; production callers should
// pass the runtime's slog logger so the warning surfaces.
func LoadKEK(log *slog.Logger) (*Cipher, error) {
	if log == nil {
		log = slog.Default()
	}
	raw := strings.TrimSpace(os.Getenv("AF_STACK_KMS_KEY"))

	if raw == "" || strings.EqualFold(raw, devKEKSentinel) {
		log.Warn("secrets: AF_STACK_KMS_KEY not set or using dev sentinel — generating deterministic dev KEK; do NOT use in production",
			"sentinel", devKEKSentinel,
			"action", "set AF_STACK_KMS_KEY to 32 random bytes hex-encoded for prod",
		)
		sum := sha256.Sum256([]byte(devKEKSeed))
		return newCipherWithKeyID(sum[:], CurrentKeyID, true)
	}

	key, err := hex.DecodeString(raw)
	if err != nil {
		return nil, fmt.Errorf("secrets: AF_STACK_KMS_KEY must be hex-encoded: %w", err)
	}
	if len(key) != kekSize {
		return nil, fmt.Errorf("secrets: AF_STACK_KMS_KEY must decode to %d bytes (got %d)", kekSize, len(key))
	}
	return newCipherWithKeyID(key, CurrentKeyID, false)
}

// NewCipherFromKey constructs a Cipher from a raw 32-byte AES key.
// Intended for tests; production code should use LoadKEK.
func NewCipherFromKey(key []byte) (*Cipher, error) {
	return newCipherWithKeyID(key, CurrentKeyID, false)
}

func newCipher(key []byte, devMode bool) (*Cipher, error) {
	return newCipherWithKeyID(key, CurrentKeyID, devMode)
}

func newCipherWithKeyID(key []byte, keyID string, devMode bool) (*Cipher, error) {
	if len(key) != kekSize {
		return nil, fmt.Errorf("secrets: KEK must be %d bytes (got %d)", kekSize, len(key))
	}
	if strings.TrimSpace(keyID) == "" {
		return nil, fmt.Errorf("secrets: kms key id is required")
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("secrets: aes init: %w", err)
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("secrets: gcm init: %w", err)
	}
	return &Cipher{aead: aead, keyID: keyID, devMode: devMode}, nil
}

// KeyID returns the kms_key_id label that should be stored alongside
// any ciphertext produced by this cipher.
func (c *Cipher) KeyID() string { return c.keyID }

// DevMode reports whether the cipher was constructed from the dev seed.
// Useful for the dashboard's "you're in dev" badge.
func (c *Cipher) DevMode() bool { return c.devMode }

// Preflight proves the cipher can seal AND open a probe value — catching
// a key that parsed but can't actually round-trip (e.g. a cloud KMS data
// key that unwrapped to the wrong length, or a corrupted AEAD). Boot
// calls this so a broken KEK fails at startup, not on the first secret
// write. Cheap: one in-memory AES-GCM round-trip.
func (c *Cipher) Preflight() error {
	probe := []byte("af-stack-kms-preflight-v1")
	sealed, err := c.Encrypt(probe)
	if err != nil {
		return fmt.Errorf("secrets: kms preflight encrypt: %w", err)
	}
	opened, err := c.Decrypt(sealed)
	if err != nil {
		return fmt.Errorf("secrets: kms preflight decrypt: %w", err)
	}
	if !bytes.Equal(opened, probe) {
		return errors.New("secrets: kms preflight round-trip mismatch")
	}
	return nil
}

// Encrypt produces a ciphertext of the form:
//
//	version_byte(1) || nonce(12) || aes-gcm-ciphertext-with-tag
//
// The associated data binds the version byte into the GCM tag so a
// downgrade attack swapping versions fails the auth check.
func (c *Cipher) Encrypt(plaintext []byte) ([]byte, error) {
	if c == nil || c.aead == nil {
		return nil, fmt.Errorf("secrets: cipher not initialised")
	}
	nonce := make([]byte, gcmNonceSize)
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, fmt.Errorf("secrets: nonce: %w", err)
	}
	aad := []byte{CipherVersionV1}
	ct := c.aead.Seal(nil, nonce, plaintext, aad)
	out := make([]byte, 0, 1+gcmNonceSize+len(ct))
	out = append(out, CipherVersionV1)
	out = append(out, nonce...)
	out = append(out, ct...)
	return out, nil
}

// Decrypt reverses Encrypt. Returns ErrInvalidCiphertext on a version
// mismatch, short header, or any GCM auth failure.
func (c *Cipher) Decrypt(envelope []byte) ([]byte, error) {
	if c == nil || c.aead == nil {
		return nil, fmt.Errorf("secrets: cipher not initialised")
	}
	if len(envelope) < 1+gcmNonceSize+c.aead.Overhead() {
		return nil, ErrInvalidCiphertext
	}
	if envelope[0] != CipherVersionV1 {
		return nil, ErrInvalidCiphertext
	}
	nonce := envelope[1 : 1+gcmNonceSize]
	ct := envelope[1+gcmNonceSize:]
	aad := []byte{CipherVersionV1}
	pt, err := c.aead.Open(nil, nonce, ct, aad)
	if err != nil {
		// Don't leak GCM error specifics to callers; they only need to
		// know the envelope didn't open.
		return nil, ErrInvalidCiphertext
	}
	return pt, nil
}
