// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-brand.mjs from brand.yaml. Do not edit.

export const brand = Object.freeze({
  name: "af-stack",
  codename: "af-stack",
  displayName: "AF Stack",
  subtitle: "Customer app",
  description: "Customer app for AF Stack.",
  logos: {
    light: "",
    dark: "",
  },
  domains: {
    dashboard: "admin.localhost",
    customerApp: "app.localhost",
    api: "api.localhost",
  },
} as const)
