// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-brand.mjs from brand.yaml. Do not edit.

export const brand = Object.freeze({
  name: "backai",
  codename: "backai",
  displayName: "SupportDesk AI",
  subtitle: "Customer app",
  description: "A polished support workflow built on the BackAI backend template.",
  logos: {
    light: "",
    dark: "",
  },
  domains: {
    dashboard: "admin.localhost",
    customerApp: "app.localhost",
    api: "api.localhost",
  },
} as const)
