// AUTO-GENERATED by scripts/generate-plugins-manifest.mjs. Do not edit by hand.
// Run `pnpm prebuild` (or it runs before `pnpm build`) to refresh this file.

export { default } from "../../../../../plugins/cost-explorer/page"
