// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-brand.mjs from brand.yaml. Do not edit.

export const brand = Object.freeze({
  name: "backai",
  codename: "backai",
  displayName: "BackAI Admin",
  subtitle: "Operator console",
  description: "Operate tenants, usage, costs, runs, keys, and billing for your AI app.",
  logos: {
    light: "",
    dark: "",
  },
  domains: {
    dashboard: "admin.localhost",
    customerApp: "app.localhost",
    api: "api.localhost",
  },
} as const)
