#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import yaml from "js-yaml"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const root = path.resolve(__dirname, "..")
const brandPath = path.join(root, "brand.yaml")

const apps = [
  {
    id: "dashboard",
    appDir: "apps/dashboard",
    surfaceKey: "dashboard",
  },
  {
    id: "customer-app",
    appDir: "apps/customer-app",
    surfaceKey: "customer_app",
  },
]

function readBrand() {
  const raw = fs.readFileSync(brandPath, "utf8")
  const parsed = yaml.load(raw)
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("brand.yaml must contain a YAML object")
  }
  return parsed
}

async function readBrandOverride() {
  const dbURL = process.env.DATABASE_URL || process.env.AF_STACK_DATABASE_URL
  if (!dbURL || process.env.BACKAI_BRAND_DB_OVERRIDE === "0") return {}
  try {
    const { Client } = await import("pg")
    const client = new Client({ connectionString: dbURL, connectionTimeoutMillis: 1000 })
    await client.connect()
    try {
      const res = await client.query("select brand from suite_brand_override where id = true")
      const brand = res.rows?.[0]?.brand
      if (brand && typeof brand === "object" && !Array.isArray(brand)) {
        return brand
      }
    } finally {
      await client.end()
    }
  } catch {
    // Brand generation must work before the runtime database is created.
    // The admin PUT writes this row; customer-app picks it up on the next
    // boot/build when the DB is reachable.
  }
  return {}
}

function mergeBrand(base, override) {
  const out = { ...base }
  for (const [key, value] of Object.entries(override ?? {})) {
    if (
      value &&
      typeof value === "object" &&
      !Array.isArray(value) &&
      out[key] &&
      typeof out[key] === "object" &&
      !Array.isArray(out[key])
    ) {
      out[key] = { ...out[key], ...value }
    } else {
      out[key] = value
    }
  }
  return out
}

function getString(obj, key, fallback = "") {
  const value = obj?.[key]
  if (typeof value === "string" && value.trim()) return value.trim()
  return fallback
}

function assertHex(value, key) {
  if (!/^#[0-9a-fA-F]{6}$/.test(value)) {
    throw new Error(`${key} must be a 6-digit hex color, got ${value}`)
  }
  return value.toUpperCase()
}

function surfaceBrand(brand, surfaceKey) {
  const surface = brand.surfaces?.[surfaceKey] ?? {}
  return {
    displayName: getString(surface, "display_name", getString(brand, "display_name")),
    subtitle: getString(surface, "subtitle", ""),
    description: getString(surface, "description", getString(brand, "short_description")),
  }
}

function writeFile(rel, contents) {
  const out = path.join(root, rel)
  fs.mkdirSync(path.dirname(out), { recursive: true })
  fs.writeFileSync(out, contents)
}

function cssFor(brand, surfaceKey) {
  const palette = brand.palette ?? {}
  const primary = assertHex(getString(palette, "primary", "#111827"), "palette.primary")
  const accent = assertHex(getString(palette, "accent", "#2563EB"), "palette.accent")
  const darkMode = palette.dark_mode !== false

  const lightAccent = surfaceKey === "dashboard" ? "#F3F4F6" : "#EFF6FF"
  const darkAccent = surfaceKey === "dashboard" ? "#1F2937" : "#172554"

  return `/* SPDX-License-Identifier: Apache-2.0 */
/* Generated by scripts/generate-brand.mjs from brand.yaml. Do not edit. */

:root {
  --brand-primary: ${primary};
  --brand-primary-foreground: #ffffff;
  --brand-accent: ${accent};
  --brand-accent-soft: ${lightAccent};
  --brand-dark-accent-soft: ${darkAccent};
}

${darkMode ? ".dark" : ":root"} {
  --brand-primary: ${accent};
  --brand-primary-foreground: #ffffff;
}
`
}

function copyLogo(brand, appDir, key, outputBaseName) {
  const configured = getString(brand.logos ?? {}, key)
  if (!configured) return ""
  const source = path.resolve(root, configured)
  if (!fs.existsSync(source)) return ""
  const ext = path.extname(source) || ".logo"
  const outputName = `${outputBaseName}${ext}`
  const publicRel = `brand/${outputName}`
  const dest = path.join(root, appDir, "public", publicRel)
  fs.mkdirSync(path.dirname(dest), { recursive: true })
  fs.copyFileSync(source, dest)
  return `/${publicRel}`
}

function brandModule(brand, app) {
  const surface = surfaceBrand(brand, app.surfaceKey)
  const lightLogo = copyLogo(brand, app.appDir, "light", "logo-light")
  const darkLogo = copyLogo(brand, app.appDir, "dark", "logo-dark")

  const publicBrand = {
    name: getString(brand, "name"),
    codename: getString(brand, "codename"),
    displayName: surface.displayName,
    subtitle: surface.subtitle,
    description: surface.description,
    logos: {
      light: lightLogo,
      dark: darkLogo,
    },
    domains: {
      dashboard: getString(brand.domains ?? {}, "dashboard"),
      customerApp: getString(brand.domains ?? {}, "customer_app"),
      api: getString(brand.domains ?? {}, "api"),
    },
  }

  const q = (value) => JSON.stringify(value)

  return `// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-brand.mjs from brand.yaml. Do not edit.

export const brand = Object.freeze({
  name: ${q(publicBrand.name)},
  codename: ${q(publicBrand.codename)},
  displayName: ${q(publicBrand.displayName)},
  subtitle: ${q(publicBrand.subtitle)},
  description: ${q(publicBrand.description)},
  logos: {
    light: ${q(publicBrand.logos.light)},
    dark: ${q(publicBrand.logos.dark)},
  },
  domains: {
    dashboard: ${q(publicBrand.domains.dashboard)},
    customerApp: ${q(publicBrand.domains.customerApp)},
    api: ${q(publicBrand.domains.api)},
  },
} as const)
`
}

async function main() {
  const brand = mergeBrand(readBrand(), await readBrandOverride())
  for (const app of apps) {
    writeFile(`${app.appDir}/src/app/brand.css`, cssFor(brand, app.surfaceKey))
    writeFile(`${app.appDir}/src/lib/brand.ts`, brandModule(brand, app))
  }
}

await main()
