#!/usr/bin/env bash
# End-to-end test for AF Stack Phase 6 multi-tenancy.
#
# What this exercises:
#   1. Enable the multi-tenancy module (apps/backend/config.yaml flag)
#   2. Bring up the runtime with the new config
#   3. Create two tenants via the admin REST API
#   4. Issue an API key per tenant; capture the one-time `value`
#   5. Call the sample agent through the gateway with each key
#   6. Audit-log isolation: querying ?tenant=<acme> returns rows for the
#      acme key only, never globex's key id
#   7. Tenant data isolation: secret written as acme is invisible to globex
#      (asserts the postgres RLS policies from Phase 6.1)
#   8. Rate limiter: send N+10 requests as one tenant, expect at least one 429
#   9. Cleanup: revoke both keys, soft-delete both tenants
#
# When MT is not wired (Phase 6.x in flight on parallel branches) the
# script SKIPs cleanly with exit 0 — useful as a CI smoke that gets
# upgraded into a real assertion once the runtime endpoints land.
#
# Usage:
#   ./scripts/test-multi-tenancy.sh
#
# Env knobs:
#   AF_STACK_PORT          — runtime port (default 8080)
#   MT_TIMEOUT_S           — wait for /health timeout (default 60)
#   MT_RATE_LIMIT_DEFAULT  — assumed default per-tenant rate (default 60)
#   MT_KEEP_STACK=1        — skip the down-step at the end (for debugging)
#   MT_SKIP_RATE_LIMIT=1   — skip the burst test (some envs don't like 70 req)

set -euo pipefail

cd "$(dirname "$0")/.."

# ── pretty output ──────────────────────────────────────────────────────────
green()  { printf "\033[32m%s\033[0m\n" "$1"; }
yellow() { printf "\033[33m%s\033[0m\n" "$1"; }
red()    { printf "\033[31m%s\033[0m\n" "$1"; }
blue()   { printf "\033[34m%s\033[0m\n" "$1"; }
step()   { printf "\n\033[1;36m==> %s\033[0m\n" "$1"; }

skip() {
    yellow "SKIP: $1"
    yellow "   (re-run once Phase 6 is fully landed)"
    exit 0
}

fail() {
    red "FAIL: $1"
    exit 1
}

# ── prerequisites ──────────────────────────────────────────────────────────
need_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        fail "required command not found: $1"
    fi
}
need_cmd docker
need_cmd curl
need_cmd jq

# ── config ────────────────────────────────────────────────────────────────
PORT="${AF_STACK_PORT:-8080}"
RUNTIME_URL="http://localhost:${PORT}"
TIMEOUT="${MT_TIMEOUT_S:-60}"
RATE_LIMIT_DEFAULT="${MT_RATE_LIMIT_DEFAULT:-60}"
CONFIG_FILE="apps/backend/config.yaml"

# Random suffix avoids collisions across reruns when soft-delete leaves
# rows behind in the tenants table.
SUFFIX="$(date +%s)-$RANDOM"
ACME_SLUG="acme-corp-${SUFFIX}"
GLOBEX_SLUG="globex-inc-${SUFFIX}"

ACME_TENANT_ID=""
GLOBEX_TENANT_ID=""
ACME_KEY_ID=""
GLOBEX_KEY_ID=""
ACME_KEY_VALUE=""
GLOBEX_KEY_VALUE=""

PASSES=0
FAILS=0

pass_step() { green "  PASS  $1"; PASSES=$((PASSES + 1)); }
fail_step() { red   "  FAIL  $1"; FAILS=$((FAILS + 1)); }

# ── 1. Enable MT in config.yaml ────────────────────────────────────────────
step "1/9  Enable multi-tenancy in ${CONFIG_FILE}"

mkdir -p "$(dirname "$CONFIG_FILE")"

# Idempotent: rewrite the file from scratch so reruns don't accumulate cruft.
# Provides both the spec-shape (suite.modules.multi-tenancy.enabled) and the
# runtime-shape (modules.enabled.multi-tenancy) so whichever the in-flight
# Phase 6.1 PR settled on, it gets honoured.
cat > "$CONFIG_FILE" <<'YAML'
# AF Stack runtime config. Generated by scripts/test-multi-tenancy.sh —
# safe to overwrite. The runtime reads modules.enabled.<id>; the spec
# shape (suite.modules.<id>.enabled) is preserved for forward compat.

modules:
  enabled:
    multi-tenancy: true
  adapters: {}
  workload_modules: []

suite:
  modules:
    multi-tenancy:
      enabled: true
      strategy: pg-rls
YAML

green "  wrote ${CONFIG_FILE} with modules.multi-tenancy.enabled: true"

# ── 2. Bring up the runtime + wait for /health ─────────────────────────────
step "2/9  docker compose up -d runtime"
docker compose up -d runtime 2>&1 | tail -5 || fail "docker compose up failed"

# Give the container a moment to mount + start.
DEADLINE=$(( $(date +%s) + TIMEOUT ))
HEALTH_OK=""
while [ "$(date +%s)" -lt "$DEADLINE" ]; do
    if HEALTH_JSON="$(curl -s --max-time 3 "${RUNTIME_URL}/health" || true)"; then
        if echo "$HEALTH_JSON" | grep -q '"status"'; then
            HEALTH_OK="yes"
            break
        fi
    fi
    sleep 2
done

if [ -z "$HEALTH_OK" ]; then
    red "runtime did not report /health within ${TIMEOUT}s"
    docker compose logs runtime --tail 40 || true
    fail "runtime never became reachable"
fi
green "  /health reachable"

# Sanity: confirm MT is what the runtime actually thinks it is.
MOD_STATE="$(curl -s --max-time 5 "${RUNTIME_URL}/api/v1/modules" || echo '{}')"
MT_ENABLED="$(echo "$MOD_STATE" | jq -r '.multi_tenancy_enabled // false')"
if [ "$MT_ENABLED" != "true" ]; then
    yellow "  /api/v1/modules reports multi_tenancy_enabled=${MT_ENABLED}"
    yellow "  raw: $MOD_STATE"
    skip "runtime not configured for multi-tenancy (config.yaml may not be mounted into the container)"
fi
green "  /api/v1/modules reports multi_tenancy_enabled=true"

# ── helpers: API access ────────────────────────────────────────────────────
# Probe whether the admin endpoints exist + accept anonymous calls from
# this localhost test. Phase 6.3 may gate them behind operator auth; we
# detect that and SKIP rather than fail noisily.
probe_admin() {
    local resp status
    resp="$(curl -s -o /tmp/.mt_probe_body -w '%{http_code}' \
        --max-time 5 "${RUNTIME_URL}/api/v1/admin/tenants" || echo "000")"
    status="$resp"
    case "$status" in
        200) return 0 ;;
        404)
            skip "admin endpoints not registered (Phase 6.3 not landed yet)"
            ;;
        401|403)
            skip "admin endpoints require operator auth; this test does not yet drive sign-in"
            ;;
        503)
            local code
            code="$(jq -r '.error.code // empty' /tmp/.mt_probe_body 2>/dev/null || echo '')"
            skip "admin endpoints returned 503 (${code:-no error code}); MT manager not wired"
            ;;
        *)
            yellow "  /api/v1/admin/tenants returned HTTP $status — assuming wired"
            return 0
            ;;
    esac
}

step "3/9  Create two tenants (acme-corp, globex-inc)"
probe_admin

create_tenant() {
    local slug="$1" name="$2"
    local body
    body="$(jq -nc --arg slug "$slug" --arg name "$name" \
        '{slug:$slug, name:$name}')"
    local resp http
    resp="$(curl -s -o /tmp/.mt_tenant -w '%{http_code}' \
        --max-time 10 \
        -X POST \
        -H 'Content-Type: application/json' \
        -d "$body" \
        "${RUNTIME_URL}/api/v1/admin/tenants" || echo "000")"
    http="$resp"
    if [ "$http" != "200" ] && [ "$http" != "201" ]; then
        red "  POST /admin/tenants returned $http"
        cat /tmp/.mt_tenant || true
        return 1
    fi
    jq -r '.id' < /tmp/.mt_tenant
}

ACME_TENANT_ID="$(create_tenant "$ACME_SLUG" "Acme Corp")" \
    || fail "could not create acme tenant"
GLOBEX_TENANT_ID="$(create_tenant "$GLOBEX_SLUG" "Globex Inc")" \
    || fail "could not create globex tenant"

if [ -z "$ACME_TENANT_ID" ] || [ "$ACME_TENANT_ID" = "null" ]; then
    fail "acme tenant id missing from response"
fi
if [ -z "$GLOBEX_TENANT_ID" ] || [ "$GLOBEX_TENANT_ID" = "null" ]; then
    fail "globex tenant id missing from response"
fi
green "  acme tenant   : $ACME_TENANT_ID ($ACME_SLUG)"
green "  globex tenant : $GLOBEX_TENANT_ID ($GLOBEX_SLUG)"

# ── 4. Issue an API key per tenant ─────────────────────────────────────────
step "4/9  Issue one API key per tenant"

issue_key() {
    local tenant_id="$1" name="$2"
    local body
    body="$(jq -nc --arg tid "$tenant_id" --arg n "$name" \
        '{tenant_id:$tid, name:$n, scopes:["agents:invoke","secrets:read","secrets:write"]}')"
    local resp http
    resp="$(curl -s -o /tmp/.mt_key -w '%{http_code}' \
        --max-time 10 \
        -X POST \
        -H 'Content-Type: application/json' \
        -d "$body" \
        "${RUNTIME_URL}/api/v1/admin/keys" || echo "000")"
    http="$resp"
    if [ "$http" != "200" ] && [ "$http" != "201" ]; then
        red "  POST /admin/keys returned $http"
        cat /tmp/.mt_key || true
        return 1
    fi
    # Returns IssuedAPIKey { id, prefix, value, ... } where value is shown ONCE.
    jq -r '"\(.id)|\(.value)"' < /tmp/.mt_key
}

ACME_KEY_PAIR="$(issue_key "$ACME_TENANT_ID" "acme-test-key")" \
    || fail "could not issue acme key"
GLOBEX_KEY_PAIR="$(issue_key "$GLOBEX_TENANT_ID" "globex-test-key")" \
    || fail "could not issue globex key"

ACME_KEY_ID="${ACME_KEY_PAIR%%|*}"
ACME_KEY_VALUE="${ACME_KEY_PAIR##*|}"
GLOBEX_KEY_ID="${GLOBEX_KEY_PAIR%%|*}"
GLOBEX_KEY_VALUE="${GLOBEX_KEY_PAIR##*|}"

if [ -z "$ACME_KEY_VALUE" ] || [ "$ACME_KEY_VALUE" = "null" ]; then
    fail "acme key value missing — one-time-reveal contract broken?"
fi
if [ -z "$GLOBEX_KEY_VALUE" ] || [ "$GLOBEX_KEY_VALUE" = "null" ]; then
    fail "globex key value missing — one-time-reveal contract broken?"
fi
green "  acme key   id=${ACME_KEY_ID}   value=${ACME_KEY_VALUE:0:12}…"
green "  globex key id=${GLOBEX_KEY_ID} value=${GLOBEX_KEY_VALUE:0:12}…"

# Confirm subsequent list does NOT include the secret value (one-time reveal).
LIST_RESP="$(curl -s --max-time 5 "${RUNTIME_URL}/api/v1/admin/keys?tenant=${ACME_TENANT_ID}")"
if echo "$LIST_RESP" | jq -e '.keys[]?.value' >/dev/null 2>&1; then
    fail_step "GET /admin/keys leaked .value (must be one-time-reveal)"
else
    pass_step "GET /admin/keys does not return .value (one-time-reveal honoured)"
fi

# ── 5. Call gateway with each key ──────────────────────────────────────────
step "5/9  Call sample.echo via the gateway with each key"

call_echo() {
    local key="$1" msg="$2"
    curl -s --max-time 10 \
        -X POST \
        -H "Authorization: Bearer ${key}" \
        -H 'Content-Type: application/json' \
        -d "{\"input\":{\"payload\":{\"message\":\"${msg}\"}}}" \
        "${RUNTIME_URL}/api/v1/agents/sample.echo"
}

ACME_ECHO="$(call_echo "$ACME_KEY_VALUE" "hello-from-acme")"
GLOBEX_ECHO="$(call_echo "$GLOBEX_KEY_VALUE" "hello-from-globex")"

if echo "$ACME_ECHO" | grep -q 'hello-from-acme\|echoed'; then
    pass_step "acme key invoked sample.echo successfully"
else
    fail_step "acme key gateway call did not return expected payload (resp: ${ACME_ECHO:0:200})"
fi
if echo "$GLOBEX_ECHO" | grep -q 'hello-from-globex\|echoed'; then
    pass_step "globex key invoked sample.echo successfully"
else
    fail_step "globex key gateway call did not return expected payload (resp: ${GLOBEX_ECHO:0:200})"
fi

# Give the audit middleware a moment to flush its writes before we query.
sleep 2

# ── 6. Audit row scope ─────────────────────────────────────────────────────
step "6/9  Audit log isolation: ?tenant=<acme> contains only acme key id"

ACME_AUDIT="$(curl -s --max-time 10 "${RUNTIME_URL}/api/v1/admin/audit?tenant=${ACME_TENANT_ID}&limit=200")"

acme_rows="$(echo "$ACME_AUDIT" | jq '.entries | length' 2>/dev/null || echo 0)"
acme_refs_acme="$(echo "$ACME_AUDIT" | jq --arg k "$ACME_KEY_ID" \
    '[.entries[] | select(.api_key_id == $k)] | length' 2>/dev/null || echo 0)"
acme_refs_globex="$(echo "$ACME_AUDIT" | jq --arg k "$GLOBEX_KEY_ID" \
    '[.entries[] | select(.api_key_id == $k)] | length' 2>/dev/null || echo 0)"

blue "  acme audit rows total=${acme_rows}, acme-key=${acme_refs_acme}, globex-key=${acme_refs_globex}"

if [ "${acme_rows:-0}" -eq 0 ]; then
    fail_step "no audit rows for acme — audit middleware not writing?"
elif [ "${acme_refs_acme:-0}" -lt 1 ]; then
    fail_step "no acme audit entries reference the acme key id"
elif [ "${acme_refs_globex:-0}" -gt 0 ]; then
    fail_step "acme audit scope leaked: ${acme_refs_globex} row(s) reference globex key id"
else
    pass_step "audit ?tenant=acme contains acme key, excludes globex key"
fi

# ── 7. Tenant isolation (RLS) ──────────────────────────────────────────────
step "7/9  Tenant data isolation: secret written as acme is invisible to globex"

# Acme writes a secret.
PUT_RESP="$(curl -s -o /tmp/.mt_secret -w '%{http_code}' \
    --max-time 10 \
    -X PUT \
    -H "Authorization: Bearer ${ACME_KEY_VALUE}" \
    -H 'Content-Type: application/json' \
    -d '{"value":"acme-only-shared-secret","description":"e2e mt test"}' \
    "${RUNTIME_URL}/api/v1/secrets/mt-test-secret" || echo "000")"

case "$PUT_RESP" in
    200|201)
        pass_step "PUT /secrets/mt-test-secret as acme returned $PUT_RESP"
        ;;
    503)
        yellow "  secrets vault not configured (503) — skipping RLS check"
        ;;
    *)
        fail_step "acme PUT secret returned HTTP $PUT_RESP (body: $(cat /tmp/.mt_secret 2>/dev/null | head -c 200))"
        ;;
esac

if [ "$PUT_RESP" = "200" ] || [ "$PUT_RESP" = "201" ]; then
    # Globex lists secrets — must not see acme's.
    GLOBEX_SECRETS="$(curl -s --max-time 10 \
        -H "Authorization: Bearer ${GLOBEX_KEY_VALUE}" \
        "${RUNTIME_URL}/api/v1/secrets")"

    globex_sees_acme="$(echo "$GLOBEX_SECRETS" | jq \
        '[.secrets[]? | select(.key == "mt-test-secret")] | length' 2>/dev/null || echo 0)"

    if [ "${globex_sees_acme:-0}" -gt 0 ]; then
        fail_step "RLS BROKEN: globex can see acme's secret \"mt-test-secret\""
    else
        pass_step "RLS holds: globex cannot see acme's secret"
    fi
fi

# ── 8. Rate limit (per-tenant) ─────────────────────────────────────────────
step "8/9  Rate limit: burst >${RATE_LIMIT_DEFAULT} requests, expect ≥1 HTTP 429"

if [ "${MT_SKIP_RATE_LIMIT:-0}" = "1" ]; then
    yellow "  MT_SKIP_RATE_LIMIT=1 set; skipping burst"
else
    BURST_COUNT=$((RATE_LIMIT_DEFAULT + 10))
    burst_429=0
    burst_2xx=0
    burst_other=0
    # Background-pipeline curl. We don't care about response bodies, just statuses.
    # The trailing newline keeps the read loop simple.
    {
        for i in $(seq 1 "$BURST_COUNT"); do
            code="$(curl -s -o /dev/null -w '%{http_code}\n' \
                --max-time 5 \
                -X POST \
                -H "Authorization: Bearer ${ACME_KEY_VALUE}" \
                -H 'Content-Type: application/json' \
                -d '{"input":{"payload":{"message":"burst"}}}' \
                "${RUNTIME_URL}/api/v1/agents/sample.echo" 2>/dev/null \
                || echo '000')"
            echo "$code"
        done
    } > /tmp/.mt_burst &
    BURST_PID=$!
    wait "$BURST_PID" || true

    while read -r code; do
        case "$code" in
            429) burst_429=$((burst_429 + 1)) ;;
            2*)  burst_2xx=$((burst_2xx + 1)) ;;
            *)   burst_other=$((burst_other + 1)) ;;
        esac
    done < /tmp/.mt_burst

    blue "  burst summary: 2xx=${burst_2xx}, 429=${burst_429}, other=${burst_other} (total ${BURST_COUNT})"

    if [ "$burst_429" -lt 1 ]; then
        fail_step "no 429 responses across ${BURST_COUNT} requests — rate limiter not engaging"
    else
        pass_step "rate limiter returned ${burst_429} HTTP 429 in burst of ${BURST_COUNT}"
    fi
fi

# ── 9. Cleanup ─────────────────────────────────────────────────────────────
step "9/9  Cleanup: revoke keys, soft-delete tenants"

revoke_key() {
    local id="$1"
    [ -n "$id" ] || return 0
    curl -s --max-time 5 -X DELETE "${RUNTIME_URL}/api/v1/admin/keys/${id}" >/dev/null || true
}
delete_tenant() {
    local id="$1"
    [ -n "$id" ] || return 0
    curl -s --max-time 5 -X DELETE "${RUNTIME_URL}/api/v1/admin/tenants/${id}" >/dev/null || true
}

revoke_key  "$ACME_KEY_ID"
revoke_key  "$GLOBEX_KEY_ID"
delete_tenant "$ACME_TENANT_ID"
delete_tenant "$GLOBEX_TENANT_ID"

green "  revoked acme + globex keys"
green "  soft-deleted acme + globex tenants"

# Drop the test secret too. Ignored if it doesn't exist or vault is off.
if [ -n "$ACME_KEY_VALUE" ]; then
    curl -s --max-time 5 -X DELETE \
        -H "Authorization: Bearer ${ACME_KEY_VALUE}" \
        "${RUNTIME_URL}/api/v1/secrets/mt-test-secret" >/dev/null || true
fi

# ── Summary ────────────────────────────────────────────────────────────────
echo
if [ "$FAILS" -eq 0 ]; then
    green "===================================================="
    green "  Multi-tenancy PASS — ${PASSES} checks passed"
    green "===================================================="
    exit 0
else
    red "===================================================="
    red "  Multi-tenancy FAIL — ${PASSES} passed, ${FAILS} failed"
    red "===================================================="
    exit 1
fi
